heat_template_version: 2013-05-23

description: >
  This template sets up a CodeReady Containers server for CI purposes.

parameters:
  name:
    type: string
    description: This name will be associated with the server and keypair.
    default: crc-test

  public_key:
    type: string
    description: Public key of the client to allow SSH authentication.

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      key_name: { get_resource: keypair }
      flavor: custom.8c.32g
      networks:
      - port: { get_resource: server_port }
      block_device_mapping:
      - device_name: "vda"
        volume_id : { get_resource: volume }
        delete_on_termination : "true"

  server_port:
    type: OS::Neutron::Port
    properties:
      network: net0

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: name }
      public_key: { get_param: public_key }

  volume:
    type: OS::Cinder::Volume
    properties:
      image: centos-7-x86_64
      size: 50
      volume_type: performance

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: external

  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: server_port }

outputs:
  server_ip:
    description: The IP of the deployed server
    value: { get_attr: [floating_ip, floating_ip_address] }
